# Generated by Django 3.1.3 on 2020-12-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='cover',
            field=models.ImageField(upload_to='product-covers'),
        ),
    ]
