# Generated by Django 3.1.3 on 2020-12-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wonder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=19)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=19)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'map_wonder',
                'ordering': ['name'],
            },
        ),
    ]
