# Generated by Django 3.1.3 on 2020-12-26 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_serial_no', models.CharField(max_length=50)),
                ('date_checked_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_paid', models.DateTimeField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=100)),
                ('cardholder_name', models.CharField(blank=True, max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('card_expiration', models.CharField(blank=True, max_length=50)),
                ('card_cvv', models.CharField(blank=True, max_length=50)),
                ('shipping_postal_code', models.PositiveIntegerField(blank=True)),
                ('shipping_street', models.CharField(blank=True, max_length=50)),
                ('shipping_district', models.CharField(blank=True, max_length=50)),
                ('shipping_ciry', models.CharField(blank=True, max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shopping_cart.shoppingcart')),
            ],
            options={
                'db_table': 'shop_payment',
                'ordering': ['date_checked_out'],
            },
        ),
    ]
