# Generated by Django 3.1.3 on 2020-12-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='gender',
        ),
    ]
