# Generated by Django 3.1.3 on 2020-12-19 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_serial_no', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'shop_shopping_cart',
                'ordering': ['date_created'],
            },
        ),
    ]
