# Generated by Django 3.1.3 on 2020-12-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product-images'),
        ),
    ]
